package com.campaignai.app

import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.lifecycle.viewModelScope
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import kotlinx.coroutines.launch
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST

data class Project(
    val id: Long = System.currentTimeMillis(),
    val businessName: String = "",
    val field: String = "",
    val product: String = "",
    val channel: String = "",
    val price: String = "",
    val directCost: String = "",
    val currentSales: String = "",
    val targetSales: String = "",
    val duration: String = "30",
    val customerTarget: String = "",
    val goal: String = "",
    val notes: String = "",
    val platforms: List<String> = emptyList()
)

data class ChatRequest(val project: Project, val mode: String, val message: String)
data class ChatResponse(val answer: String)

interface Api {
    @POST("chat")
    suspend fun chat(@Body request: ChatRequest): ChatResponse
}

class AppVM : ViewModel() {
    var projects by mutableStateOf(listOf<Project>())
    var current by mutableStateOf(Project())
    var messages by mutableStateOf(listOf<Pair<String,String>>())
    var busy by mutableStateOf(false)
    var lastGenerated by mutableStateOf("")

    private val api = Retrofit.Builder()
        .baseUrl(BuildConfig.API_BASE_URL)
        .addConverterFactory(GsonConverterFactory.create())
        .build().create(Api::class.java)

    fun load(context: Context) {
        val raw = context.getSharedPreferences("campaign_ai", Context.MODE_PRIVATE)
            .getString("projects", "[]") ?: "[]"
        projects = try {
            Gson().fromJson(raw, object : TypeToken<List<Project>>(){}.type)
        } catch (_: Exception) { emptyList() }
    }

    fun save(context: Context) {
        context.getSharedPreferences("campaign_ai", Context.MODE_PRIVATE)
            .edit().putString("projects", Gson().toJson(projects)).apply()
    }

    fun upsert(context: Context) {
        projects = (projects.filterNot { it.id == current.id } + current).takeLast(100)
        save(context)
    }

    fun newProject() { current = Project() }

    fun askInScope(mode: String, text: String) { viewModelScope.launch { ask(mode, text) } }

    suspend fun ask(mode: String, text: String) {
        if (text.isBlank()) return
        messages = messages + ("شما" to text)
        busy = true
        try {
            val r = api.chat(ChatRequest(current, mode, text))
            messages = messages + ("AI" to r.answer)
            lastGenerated = r.answer
        } catch (_: Exception) {
            messages = messages + ("AI" to "اتصال به Backend برقرار نشد. آدرس API و روشن بودن سرور را بررسی کن.")
        } finally { busy = false }
    }
}

@Composable
fun App() {
    val vm: AppVM = viewModel()
    val ctx = androidx.compose.ui.platform.LocalContext.current
    LaunchedEffect(Unit) { vm.load(ctx) }
    var page by remember { mutableStateOf("home") }

    MaterialTheme {
        Scaffold(
            bottomBar = {
                NavigationBar {
                    listOf(
                        "home" to "خانه", "projects" to "پروژه‌ها",
                        "design" to "طراحی", "questions" to "سوال‌ها",
                        "ai" to "AI"
                    ).forEach {
                        NavigationBarItem(
                            selected = page == it.first,
                            onClick = { page = it.first },
                            icon = {},
                            label = { Text(it.second) }
                        )
                    }
                }
            }
        ) { pad ->
            Box(Modifier.padding(pad).fillMaxSize()) {
                when(page) {
                    "home" -> Home(vm) { page = "projects" }
                    "projects" -> Projects(vm, ctx) { vm.current = it; page = "design" }
                    "design" -> Design(vm, ctx)
                    "questions" -> Questions(vm)
                    "ai" -> AIChat(vm)
                }
            }
        }
    }
}

@Composable
fun Home(vm: AppVM, go: () -> Unit) {
    Column(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) {
        Text("Campaign AI", style=MaterialTheme.typography.headlineLarge)
        Text("دستیار کامل طراحی و مدیریت کمپین فروش 🚀")
        Button(onClick={vm.newProject(); go()}, Modifier.fillMaxWidth()) { Text("شروع پروژه جدید") }
        OutlinedButton(onClick=go, Modifier.fillMaxWidth()) { Text("پروژه‌های من") }
        Card(Modifier.fillMaxWidth()) {
            Column(Modifier.padding(16.dp), verticalArrangement=Arrangement.spacedBy(7.dp)) {
                Text("ماژول‌های اصلی", style=MaterialTheme.typography.titleLarge)
                Text("تحلیل کسب‌وکار • مشتری • Insight • Offer • Funnel • محتوا • KPI")
                Text("اقتصاد کمپین • CAC • LTV • ROAS • ROI • A/B Test • Optimization")
                Text("Proposal • قرارداد • گزارش • دستیار AI")
            }
        }
    }
}

@Composable
fun Projects(vm: AppVM, ctx: Context, open: (Project)->Unit) {
    Column(Modifier.padding(16.dp)) {
        Row(Modifier.fillMaxWidth(), horizontalArrangement=Arrangement.SpaceBetween) {
            Text("پروژه‌ها", style=MaterialTheme.typography.headlineSmall)
            Button(onClick={vm.newProject(); open(vm.current)}) { Text("جدید") }
        }
        LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)) {
            items(vm.projects) { p ->
                Card(onClick={ open(p) }, Modifier.fillMaxWidth()) {
                    Column(Modifier.padding(14.dp)) {
                        Text(if(p.businessName.isBlank()) "پروژه بدون نام" else p.businessName)
                        Text(p.product.ifBlank {"محصول مشخص نشده"})
                        Text("هدف: ${p.goal.ifBlank{"تعیین نشده"}}")
                    }
                }
            }
        }
    }
}

private val MESSENGER_PLATFORMS = listOf(
    "Telegram", "WhatsApp", "Instagram", "Eitaa", "Rubika", "Bale",
    "Soroush Plus", "Gap", "iGap", "Signal", "Discord", "Viber",
    "LINE", "WeChat", "Snapchat", "Facebook Messenger", "TikTok",
    "YouTube", "X", "LinkedIn", "Pinterest", "Reddit", "Other / Custom"
)

@Composable
fun MessengerSelector(vm: AppVM) {
    val selected = vm.current.platforms.toSet()
    Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
        Text("کانال‌های کمپین 📱", style = MaterialTheme.typography.titleLarge)
        Text("یک یا چند پلتفرم را انتخاب کن. AI برای هر کانال، استراتژی، محتوا، CTA و روش اندازه‌گیری متناسب پیشنهاد می‌دهد.")
        MESSENGER_PLATFORMS.forEach { platform ->
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(platform, Modifier.padding(vertical = 8.dp))
                Checkbox(
                    checked = platform in selected,
                    onCheckedChange = { checked ->
                        val next = if (checked) selected + platform else selected - platform
                        vm.current = vm.current.copy(platforms = next.toList())
                    }
                )
            }
        }
        if (selected.isNotEmpty()) {
            Text("انتخاب‌شده: ${selected.joinToString(" • " )}",
                style = MaterialTheme.typography.bodySmall)
        }
    }
}

@Composable
fun Design(vm: AppVM, ctx: Context) {
    var mode by remember { mutableStateOf("campaign") }
    val modes = listOf(
        "campaign" to "🚀 طراحی کامل کمپین",
        "audit" to "🔎 تحلیل کسب‌وکار",
        "customer" to "👥 تحلیل مشتری و Insight",
        "content" to "✍️ تولید محتوا",
        "finance" to "💰 اقتصاد و KPI",
        "optimize" to "📈 تست و بهینه‌سازی",
        "proposal" to "📄 Proposal",
        "contract" to "📝 قرارداد",
        "report" to "📊 گزارش"
    )
    Column(Modifier.padding(14.dp), verticalArrangement=Arrangement.spacedBy(8.dp)) {
        Text("ابزارهای کمپین", style=MaterialTheme.typography.headlineSmall)
        LazyColumn(Modifier.weight(1f), verticalArrangement=Arrangement.spacedBy(8.dp)) {
            item { MessengerSelector(vm) }
            items(modes) { (key,label) ->
                Button(onClick={
                    mode=key
                    val prompt = when(key) {
                        "campaign" -> "با توجه به اطلاعات پروژه، یک کمپین کامل طراحی کن. برای کانال‌های انتخاب‌شده نقش و استراتژی جداگانه بده و تفاوت فرمت محتوا، CTA، funnel و اندازه‌گیری را برای هر کانال در نظر بگیر. اگر داده‌ای ضروری کم است، ابتدا فقط همان سوال‌ها را مشخص کن. خروجی: تحلیل وضعیت، هدف، مخاطب، insight، offer، ایده، استراتژی، funnel، کانال‌ها، برنامه محتوا، CTA، KPI، بودجه و روش اندازه‌گیری."
                        "audit" -> "کسب‌وکار را مثل یک Campaign Manager حرفه‌ای Audit کن و نقاط قوت، مشکل اصلی، گلوگاه فروش، داده‌های ناقص و فرصت کمپین را مشخص کن."
                        "customer" -> "مشتری هدف را تحلیل کن و Persona، نیاز، محرک خرید، موانع خرید، اعتراض‌ها و Insight قابل استفاده در کمپین بده."
                        "content" -> "برای این پروژه 10 Hook، چند متن تبلیغاتی، ایده ویدئو، CTA و یک تقویم محتوایی مناسب طراحی کن."
                        "finance" -> "اقتصاد کمپین را بررسی کن. قیمت، هزینه مستقیم، سود ناخالص، CAC قابل قبول، بودجه، LTV، ROAS و ROI را در صورت وجود داده محاسبه کن و داده‌های ناقص را جدا کن."
                        "optimize" -> "یک برنامه A/B Test و Optimization برای این کمپین طراحی کن و بگو چه چیزی، چرا و چگونه اندازه‌گیری شود."
                        "proposal" -> "یک Proposal حرفه‌ای و قابل ارائه به صاحب کسب‌وکار برای این کمپین آماده کن."
                        "contract" -> "یک پیش‌نویس قرارداد همکاری کمپین بر اساس اطلاعات پروژه آماده کن و موارد مبهم را علامت بزن."
                        else -> "یک گزارش حرفه‌ای کمپین طراحی کن. بخش‌های هدف، اقدامات، KPI، نتایج، تحلیل، اقتصاد، مشکلات و پیشنهاد بعدی را در قالب قابل ارائه تنظیم کن."
                    }
                    vm.askInScope(key, prompt)
                }, Modifier.fillMaxWidth()) { Text(label) }
            }
        }
        Text("پروژه فعلی: ${vm.current.businessName.ifBlank{"بدون نام"}}")
    }
}

@Composable
fun Questions(vm: AppVM) {
    val qs = listOf(
        "هدف دقیق کمپین چیست و تا چه تاریخی؟",
        "پرفروش‌ترین محصول یا خدمت چیست؟",
        "قیمت فروش و هزینه مستقیم هر فروش چقدر است؟",
        "فروش فعلی در ماه/هفته چقدر است؟",
        "ظرفیت تأمین و پاسخ‌گویی به سفارش بیشتر چقدر است؟",
        "مشتری اصلی چه ویژگی‌هایی دارد؟",
        "مشتری دقیقاً چه نیازی را حل می‌کند؟",
        "مشتری قبل از خرید بیشتر درباره چه چیزی سؤال می‌کند؟",
        "مهم‌ترین دلیل انتخاب شما نسبت به رقبا چیست؟",
        "مهم‌ترین دلیل نخریدن یا تعویق خرید چیست؟",
        "چه مدرکی برای اثبات کیفیت یا اعتماد دارید؟",
        "چه تخفیف، هدیه، ضمانت یا خدمت اضافه‌ای قابل ارائه است؟",
        "چه محدودیت‌هایی در قیمت، موجودی، محتوا، بودجه یا کانال دارید؟",
        "فروش و سفارش چگونه ثبت می‌شود؟",
        "چطور فروش کمپین از فروش عادی تشخیص داده می‌شود؟",
        "قوانین مرجوعی/تعویض چیست؟",
        "هزینه تبلیغات را چه کسی پرداخت می‌کند؟",
        "نتیجه کمپین بر اساس فروش، سود یا مشتری جدید سنجیده می‌شود؟"
    )
    Column(Modifier.padding(16.dp)) {
        Text("بانک سوال Campaign Manager", style=MaterialTheme.typography.headlineSmall)
        Text("AI باید ابتدا اطلاعات موجود را بخواند و سوال‌های تکراری را حذف کند.")
        LazyColumn(Modifier.padding(top=10.dp), verticalArrangement=Arrangement.spacedBy(7.dp)) {
            items(qs) { q -> Card(Modifier.fillMaxWidth()) { Text(q, Modifier.padding(14.dp)) } }
        }
    }
}

@Composable
fun AIChat(vm: AppVM) {
    var input by remember { mutableStateOf("") }
    val scope = rememberCoroutineScope()
    Column(Modifier.fillMaxSize().padding(12.dp)) {
        Text("دستیار Campaign AI 🤖", style=MaterialTheme.typography.headlineSmall)
        Text("سوالت را درباره پروژه فعلی بپرس.")
        LazyColumn(Modifier.weight(1f), contentPadding=PaddingValues(vertical=8.dp)) {
            items(vm.messages) { (who,msg) ->
                Card(Modifier.fillMaxWidth().padding(vertical=4.dp)) {
                    Column(Modifier.padding(12.dp)) {
                        Text(who, style=MaterialTheme.typography.labelLarge)
                        Text(msg)
                    }
                }
            }
        }
        Row(horizontalArrangement=Arrangement.spacedBy(7.dp)) {
            OutlinedTextField(input,{input=it},Modifier.weight(1f),placeholder={Text("مثلاً کمپین این محصول را طراحی کن")})
            Button(enabled=!vm.busy,onClick={val q=input; input=""; scope.launch{vm.ask("assistant",q)}}){Text("ارسال")}
        }
    }
}

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { App() }
    }
}
